//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 05:09:39 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.webservicesoap.org/birthday", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bwagih.soapWSDemo.model.generation.greeting;
